services:
  anilist-linker:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    container_name: anilist-linker-dev
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/app/logs
