# .github/workflows/docker-publish.yml

name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use a fresh Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checkout the repository code

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Your GitHub username
          password: ${{ secrets.GITHUB_TOKEN }} # GitHub's automatically provided token

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Set up Docker Buildx for multi-platform builds (optional but good practice)

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # The build context is the root of the repository
          file: ./docker/Dockerfile # Path to your Dockerfile
          push: true # Push the image to the registry
          tags: | # Define image tags
            ghcr.io/${{ github.repository }}:latest # Tag as 'latest'
            ghcr.io/${{ github.repository }}:${{ github.sha }} # Tag with the commit SHA (for unique versions)
          cache-from: type=gha # Cache layers to speed up subsequent builds
          cache-to: type=gha,mode=max # Store cache for future builds
